/* AlpenSMP Admin rufen */
(function(){if(window.__alpenAdminCall)return;window.__alpenAdminCall=true;var COOL_MS=300000,MIN_LEN=5,MAX_LEN=300,submitting=false,coolUntil=0,tickTimer=null;
function ready(fn){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",fn);else fn();}
function playerKey(name){return String(name||"").trim().toLowerCase().replace(/[.#$\[\]\/]/g,"_").slice(0,40);}
function fmtRemain(ms){var s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60),r=s%60;return m+":"+String(r).padStart(2,"0");}
function fmtWords(ms){var s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60),r=s%60;if(m<=0)return r+" Sekunden";return m+" Minute"+(m===1?"":"n")+" und "+r+" Sekunde"+(r===1?"":"n");}
function hint(msg,ok){var el=document.getElementById("adminCallHint");if(!el)return;el.textContent=msg||"";el.style.color=ok?"#34d399":"";}
function setDisabled(on,remainMs){var btn=document.getElementById("adminCallBtn");if(!btn)return;btn.disabled=!!on;btn.style.opacity=on?"0.55":"";btn.style.pointerEvents=on?"none":"";btn.textContent=on&&remainMs>0?(" "+fmtRemain(remainMs)):"Admin rufen";}
function inject(){if(document.getElementById("adminCallBox"))return;var host=document.querySelector(".ticket-box")||document.querySelector("#impressum");if(!host||!host.parentNode)return;var box=document.createElement("div");box.id="adminCallBox";box.className=host.className;box.style.maxWidth="640px";box.style.marginTop="18px";box.innerHTML="<h3 style=\"font-family:Outfit,system-ui,sans-serif;margin-bottom:8px\">Admin rufen</h3><p style=\"color:var(--text2);line-height:1.7;margin-bottom:14px\">Du brauchst Hilfe von einem Teammitglied?</p><label style=\"display:block;font-size:.82rem;color:var(--muted);margin-bottom:6px\">Spielername</label><input id=\"adminCallName\" maxlength=\"32\" placeholder=\"Dein Ingame-Name\" style=\"width:100%;margin-bottom:10px\"><label style=\"display:block;font-size:.82rem;color:var(--muted);margin-bottom:6px\">Grund</label><textarea id=\"adminCallReason\" maxlength=\"300\" placeholder=\"Beschreibe kurz dein Anliegen...\" style=\"width:100%;min-height:90px\"></textarea><p id=\"adminCallHint\" class=\"form-note\" style=\"margin:10px 0\"></p><button class=\"btn btn-primary\" type=\"button\" id=\"adminCallBtn\">Admin rufen</button>";if(host.nextSibling)host.parentNode.insertBefore(box,host.nextSibling);else host.parentNode.appendChild(box);var tn=document.getElementById("ticketName"),an=document.getElementById("adminCallName");if(tn&&an&&tn.value&&!an.value)an.value=tn.value;document.getElementById("adminCallBtn").addEventListener("click",submit);startCooldownWatch();}
function startCooldownWatch(){var name=(document.getElementById("adminCallName")||{}).value||"";var key=playerKey(name);if(!window.db||!key){setDisabled(false,0);return;}db.ref("adminCallCooldown/"+key).on("value",function(snap){var last=snap.val()||0;coolUntil=last?Number(last)+COOL_MS:0;tick();});var nameInp=document.getElementById("adminCallName");if(nameInp&&!nameInp.__bound){nameInp.__bound=true;nameInp.addEventListener("change",startCooldownWatch);nameInp.addEventListener("blur",startCooldownWatch);}}
function tick(){function loop(){var left=coolUntil-Date.now();if(left>0){setDisabled(true,left);hint("Du hast bereits eine Anfrage gesendet. Bitte warte noch "+fmtWords(left)+".");requestAnimationFrame(loop);}else setDisabled(false,0);}loop();}
function submit(){if(submitting)return;if(!window.db){hint("Verbindung fehlt.");return;}var name=((document.getElementById("adminCallName")||{}).value||"").trim().slice(0,32);var reason=((document.getElementById("adminCallReason")||{}).value||"").trim();if(!name){hint("Bitte deinen Spielernamen angeben.");return;}if(reason.length<MIN_LEN){hint("Der Grund muss mindestens 5 Zeichen haben.");return;}if(reason.length>MAX_LEN){hint("Maximal 300 Zeichen.");return;}var key=playerKey(name);submitting=true;setDisabled(true,COOL_MS);hint("Sende...");db.ref("adminCallCooldown/"+key).transaction(function(cur){var now=Date.now();if(cur&&now-Number(cur)<COOL_MS)return;return now;}).then(function(res){if(!res.committed){var last=res.snapshot&&res.snapshot.val?Number(res.snapshot.val()):Date.now();coolUntil=last+COOL_MS;hint("Du hast bereits eine Anfrage gesendet. Bitte warte noch "+fmtWords(Math.max(0,coolUntil-Date.now()))+".");submitting=false;tick();return;}var payload={type:"admin_call",by:name,msg:reason,reason:reason,status:"open",ts:Date.now(),source:"website-admin-call",replies:{}};return db.ref("helpRequests").push(payload).then(function(ref){return db.ref("staffAlerts").push({kind:"admin_call",player:name,reason:reason,helpKey:ref.key,ts:Date.now(),seen:false});}).then(function(){document.getElementById("adminCallReason").value="";coolUntil=Date.now()+COOL_MS;hint("Deine Anfrage wurde an das Team gesendet. Du kannst erst in "+fmtRemain(COOL_MS)+" eine neue Anfrage senden.",true);submitting=false;tick();});}).catch(function(){submitting=false;setDisabled(false,0);hint("Senden fehlgeschlagen. Bitte spaeter erneut versuchen.");});}
ready(inject);})();
