/* Team Admin-Anfragen */
(function(){if(window.__alpenAdminCallsTeam)return;window.__alpenAdminCallsTeam=true;var lastAlertTs=Number(sessionStorage.getItem("alpenLastAlertTs")||"0");
function ago(ts){var d=Date.now()-(ts||0);if(d<60000)return"gerade eben";if(d<3600000)return"vor "+Math.floor(d/60000)+" Min.";if(d<86400000)return"vor "+Math.floor(d/3600000)+" Std.";return typeof formatDate==="function"?formatDate(ts):new Date(ts).toLocaleString("de-DE");}
function sourceLabel(item){var s=(item.source||item.sourceLabel||"").toLowerCase();if(s.indexOf("minecraft")!==-1||item.type==="admin_call"&&s.indexOf("website")===-1&&item.uuid)return"Minecraft Ingame";if(s.indexOf("website")!==-1||item.ticketCode)return"Website";if(item.type==="admin_call")return item.sourceLabel||"Admin-Call";return item.source||"Website";}
function statusLabel(item){var st=item.status||(item.claimedBy?"claimed":"open");if(st==="done"||st==="erledigt")return{t:"Erledigt"};if(st==="claimed"||st==="in_progress"||item.claimedBy)return{t:"In Bearbeitung"};return{t:"Offen"};}
function enhance(){var h=document.querySelector("#tab-help h2");if(h)h.textContent="Admin-Anfragen & Hilfe";var d=document.querySelector("#tab-help .desc");if(d)d.textContent="Spieler-Rufe aus Minecraft und Website-Tickets.";}
window.loadHelp=function(){enhance();if(!window.db)return;db.ref("helpRequests").once("value").then(function(snap){var data=snap.val()||{};var entries=Object.entries(data).filter(function(p){return!p[1].archived;}).reverse();var el=document.getElementById("helpList");if(!el)return;if(!entries.length){el.innerHTML='<div class="empty">Keine offenen Anfragen</div>';return;}var can=currentUser&&(currentUser.role==="owner"||currentUser.role==="admin"||currentUser.role==="moderator"||currentUser.role==="helper");el.innerHTML=entries.map(function(pair){var key=pair[0],item=pair[1],st=statusLabel(item);var replies="";if(item.replies)replies=Object.values(item.replies).map(function(r){return"<div style=\"margin-top:8px;padding:10px;background:rgba(0,0,0,.3);border-radius:9px;font-size:.9rem\"><strong>"+esc(r.by)+"</strong>: "+esc(r.text)+"</div>";}).join("");var kind=item.type==="admin_call"?"Admin-Anfrage":"Hilfe";var extra=item.claimedBy?"<div class=\"meta\">Zustaendig: "+esc(item.claimedBy)+"</div>":"";var meta=[];if(item.requestId)meta.push("ID #"+item.requestId);if(item.uuid)meta.push("UUID "+item.uuid);if(item.server)meta.push(item.server);var btns="";if(can){btns="<div style=\"margin-top:12px;display:flex;gap:8px;flex-wrap:wrap\">"+((item.status==="open"||!item.status||item.status==="offen")&&!item.claimedBy?"<button class=\"btn btn-sm\" onclick=\"claimAdminCall('"+key+"')\">Uebernehmen</button>":"")+(item.status!=="done"&&item.status!=="erledigt"?"<button class=\"btn btn-sm\" onclick=\"doneAdminCall('"+key+"')\">Erledigt</button>":"")+"<input type=\"text\" id=\"reply-"+key+"\" placeholder=\"Antwort...\" style=\"margin:0;flex:1\"><button class=\"btn btn-sm\" onclick=\"replyHelp('"+key+"')\">Antworten</button><button class=\"btn btn-ghost btn-sm\" onclick=\"removeItem('helpRequests','"+key+"')\">Archiv</button></div>";}return"<div class=\"panic-item\"><div><strong>"+kind+"</strong></div><div class=\"meta\">Quelle: "+esc(sourceLabel(item))+"</div><div>Spieler: <strong>"+esc(item.by)+"</strong></div><div style=\"margin:8px 0\">Grund: "+esc(item.reason||item.msg)+"</div><div class=\"meta\">Gesendet: "+esc(ago(item.ts))+(meta.length?" · "+esc(meta.join(" · ")):"")+"</div><div style=\"margin-top:6px;font-weight:700\">Status: "+st.t+"</div>"+extra+replies+btns+"</div>";}).join("");});};
window.claimAdminCall=function(key){if(!currentUser)return;db.ref("helpRequests/"+key).update({status:"claimed",claimedBy:currentUser.username,claimedAt:Date.now()}).then(function(){toast("Uebernommen");loadHelp();});};
window.doneAdminCall=function(key){if(!currentUser)return;db.ref("helpRequests/"+key).update({status:"done",doneBy:currentUser.username,doneAt:Date.now()}).then(function(){toast("Erledigt");loadHelp();});};
function listenAlerts(){if(!window.db||!currentUser)return;db.ref("staffAlerts").limitToLast(8).on("child_added",function(snap){var a=snap.val()||{};if(!a.ts||a.ts<=lastAlertTs)return;lastAlertTs=a.ts;sessionStorage.setItem("alpenLastAlertTs",String(lastAlertTs));if(a.kind!=="admin_call")return;if(typeof toast==="function")toast("Neue Admin-Anfrage: "+(a.player||"")+" braucht Hilfe.");var n=document.createElement("div");n.style.cssText="position:fixed;right:16px;bottom:16px;z-index:80;background:rgba(12,16,24,.96);border:1px solid rgba(199,62,62,.45);border-radius:14px;padding:14px 16px;max-width:320px";n.innerHTML="<strong>Neue Admin-Anfrage</strong><div style=\"margin:6px 0;color:#9aa3b2\">"+(a.player||"Spieler")+" benoetigt Hilfe.</div><button class=\"btn btn-sm\" type=\"button\">Anfrage ansehen</button>";n.querySelector("button").onclick=function(){n.remove();if(typeof showTab==="function")showTab("help");};document.body.appendChild(n);setTimeout(function(){if(n.parentNode)n.remove();},12000);});}
function loadScriptDone(){enhance();if(currentUser)listenAlerts();if(document.getElementById("tab-help")&&!document.getElementById("tab-help").classList.contains("hidden"))loadHelp();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(loadScriptDone,500);});else setTimeout(loadScriptDone,500);})();
