(function(){if(document.querySelector('script[data-alpen-version]'))return;var s=document.createElement('script');s.src='https://alpensmp.net/version-badge.js?v=12';s.setAttribute('data-alpen-version','1');document.head.appendChild(s);})();
window.ALPEN_GUIDE={version:"0.7",server:{ip:"alpensmp.falixsrv.me",bedrockPort:"27491",version:"1.21.11",discord:"https://discord.gg/FfR56Ddtj8",rules:"https://alpensmp.net/regeln/"},chapters:[
{id:"mc-was",track:"mc",kind:"minecraft",active:true,order:10,icon:"\u26cf\ufe0f",title:"Was ist Minecraft?",description:"Welt aus Blöcken – bauen, erkunden, sammeln, überleben.",keywords:"minecraft grundlagen",html:"<p>Minecraft ist ein Spiel in einer Welt aus Würfeln (Blöcken). Du kannst abbauen, bauen, Ressourcen sammeln, Tiere züchten, Höhlen erkunden und nachts gegen Monster bestehen.</p>"},
{id:"mc-minuten",track:"mc",kind:"minecraft",active:true,order:20,icon:"\u23f1\ufe0f",title:"Deine ersten Minuten",description:"Sieben einfache Schritte für den Start.",keywords:"holz haus",html:"<ol class='steps'><li>Holz sammeln</li><li>Werkbank bauen</li><li>Unterkunft mit Tür und Fackeln</li></ol>"},
{id:"mc-survive",track:"mc",kind:"minecraft",active:true,order:40,icon:"\u2764\ufe0f",title:"Überleben",description:"Herzen, Hunger, Nacht und Monster.",keywords:"hunger creeper",html:"<p>Ohne Hunger keine Regeneration. Monster spawnen im Dunkeln. Creeper explodieren in der Nähe.</p>"},
{id:"alpen-willkommen",track:"alpen",kind:"alpensmp",active:true,order:100,icon:"\ud83c\udfd4\ufe0f",title:"Willkommen auf AlpenSMP",description:"Survival für Java und Bedrock.",keywords:"willkommen",html:"<p>Deutschsprachiger Survival-Server, gemeinsame Welt, keine Pay-to-Win-Mechaniken. Claims, Voice optional, Homes, TPA, RTP, Gräber.</p>"},
{id:"alpen-join",track:"alpen",kind:"alpensmp",active:true,order:110,icon:"\ud83c\udf10",title:"Server beitreten",description:"IP, Port, Version.",keywords:"join ip bedrock",html:"<p>Java: <code>alpensmp.falixsrv.me</code><br>Bedrock: dieselbe Adresse, Port <code>27491</code><br>Empfohlen: 1.21.11</p>"},
{id:"alpen-regeln",track:"alpen",kind:"alpensmp",active:true,order:120,icon:"\ud83d\udcdc",title:"Server-Regeln",description:"Immer das offizielle Regelwerk nutzen.",keywords:"regeln",html:"<p><a class='btn btn-p' href='https://alpensmp.net/regeln/'>Offizielle Server-Regeln</a></p>"},
{id:"alpen-voice",track:"alpen",kind:"alpensmp",active:true,order:140,icon:"\ud83c\udf99\ufe0f",title:"Voice Chat",description:"Simple Voice Chat, optional.",keywords:"voice",html:"<p>Nähe-basierte Sprache. Ohne Mod kannst du trotzdem joinen. Java-Mod passend zu 1.21.11 (Modrinth).</p>"},
{id:"alpen-commands",track:"alpen",kind:"alpensmp",active:true,order:150,icon:"\ud83d\udee0\ufe0f",title:"Wichtige Befehle",description:"Nur bestätigte Commands.",keywords:"spawn home tpa",html:"<p><code>/spawn</code> <code>/sethome</code> <code>/home</code> <code>/homes</code> <code>/tpa</code> <code>/back</code> <code>/rtp</code> <code>/msg</code> <code>/call admin</code></p>"}
]};
