/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as KarteRouteImport } from './routes/karte'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as RegelnRouteImport } from './routes/regeln'
import { Route as ServerRouteImport } from './routes/server'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const KarteRoute = KarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegelnRoute = RegelnRouteImport.update({
  id: '/regeln',
  path: '/regeln',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/guide': typeof GuideRoute
  '/karte': typeof KarteRoute
  '/kontakt': typeof KontaktRoute
  '/regeln': typeof RegelnRoute
  '/server': typeof ServerRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/guide': typeof GuideRoute
  '/karte': typeof KarteRoute
  '/kontakt': typeof KontaktRoute
  '/regeln': typeof RegelnRoute
  '/server': typeof ServerRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/guide': typeof GuideRoute
  '/karte': typeof KarteRoute
  '/kontakt': typeof KontaktRoute
  '/regeln': typeof RegelnRoute
  '/server': typeof ServerRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/faq'
    | '/features'
    | '/guide'
    | '/karte'
    | '/kontakt'
    | '/regeln'
    | '/server'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/faq'
    | '/features'
    | '/guide'
    | '/karte'
    | '/kontakt'
    | '/regeln'
    | '/server'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/faq'
    | '/features'
    | '/guide'
    | '/karte'
    | '/kontakt'
    | '/regeln'
    | '/server'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  GuideRoute: typeof GuideRoute
  KarteRoute: typeof KarteRoute
  KontaktRoute: typeof KontaktRoute
  RegelnRoute: typeof RegelnRoute
  ServerRoute: typeof ServerRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karte': {
      id: '/karte'
      path: '/karte'
      fullPath: '/karte'
      preLoaderRoute: typeof KarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regeln': {
      id: '/regeln'
      path: '/regeln'
      fullPath: '/regeln'
      preLoaderRoute: typeof RegelnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  GuideRoute: GuideRoute,
  KarteRoute: KarteRoute,
  KontaktRoute: KontaktRoute,
  RegelnRoute: RegelnRoute,
  ServerRoute: ServerRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
